### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-tests-stubs#11]
Please tag missing releases

tags: https://github.com/php-stubs/wordpress-tests-stubs/tags
releases: https://github.com/php-stubs/wordpress-tests-stubs/commits/master/

**Comment by szepeviktor** [comment]
From [5.4.14](https://github.com/php-stubs/wordpress-tests-stubs/commit/6e61fd7f4950c20f56651b0dd76540458a95f470) on ...

**Comment by swissspidy** [comment]
Whoops, forgot to push the tags. Thanks!

**Comment by swissspidy** [comment]
Looks like Packagist didn't pick up the tags yet 🙄 

@szepeviktor Could you please go to https://packagist.org/packages/php-stubs/wordpress-tests-stubs and click the Update button? Thanks!

**Comment by szepeviktor** [comment]
Success!
