### ISSUE TITLE
Cache function in stubs

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-tests-stubs#12]
@swissspidy Am I right we don't need `wp_cache_*` functions in these stubs?

**Comment by swissspidy** [comment]
These functions are always available & usable, even if not using an external object cache.

**Comment by szepeviktor** [comment]
The thing is these functions are already in core stubs.
I've put both of them in `stubFiles:` and they collided.

It would be `->notPath('object-cache.php')` in the finder.

**Comment by swissspidy** [comment]
Oh I see! Yes I think in that case they can probably be removed
