### ISSUE TITLE
Executing stubs fail because the lack of PHPUnit

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/wordpress-tests-stubs#3]
The last test step is to execute stubs. `php -f wordpress-tests-stubs.php`
It fails. https://app.travis-ci.com/github/php-stubs/wordpress-tests-stubs./jobs/547182050

@stevegrunwell What PHPUnit versions do WordPress people use?
https://phpunit.de/supported-versions.html

PHP 7.4
PHP 7.3
PHP 7.2
PHP 7.1

**Comment by szepeviktor** [comment]
There are so many external classes extended I won't test stubs execution.
https://app.travis-ci.com/github/php-stubs/wordpress-tests-stubs./jobs/547185007

**Comment by szepeviktor** [comment]
Finally there is a way....

**Comment by stevegrunwell** [comment]
Officially, WordPress uses PHPUnit 5.x or newer, but has very recently (WordPress 5.8.x) undergone a change: moving forward, tests should be written against the latest releases of PHPUnit (9.x), with https://github.com/Yoast/PHPUnit-Polyfills/ handling the incompatibilities between versions of PHPUnit.

Full details on the newer testing apparatus: https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/
